### PR TITLE
biggest warnings reduce and typing. 

### PR DESCRIPTION
**Pull request by noverd**
Before: 200 warns
Now: 114 warns

### CODE REVIEW

**Comment by noverd** [comment]
Also i wanna convert Brain and anothers to dataclasses, to reduce memory-use with slots.

**Comment by apocas** [comment]
It's looking good!

**Comment by noverd** [comment]
@apocas what do you think about adding mypy to the project?

**Comment by noverd** [comment]
Ready to merge

**Comment by apocas** [comment]
Problem with static typing in Python is circular dependency.
Now we have project->vectorbd.tools->project :(

**Comment by noverd** [comment]
> Problem with static typing in Python is circular dependency. Now we have project->vectorbd.tools->project :(

oh...

**Comment by noverd** [comment]
sorry for it

**Pull request merged**
