### PR TITLE
Llamaindex

### PR DESCRIPTION
**Pull request by apocas**

### CODE REVIEW

**Comment by gbrian** [comment]
LOL! was going to push a change for ingesting url and was crazy as code was different from project that just forked 5 mins ago!! :D You are fast!!!  
Promising project, thanks!

**Comment by apocas** [comment]
Eheheh yeah I'm having fun :D

**Comment by gbrian** [comment]
Me tooo!!
I'll create a post soon! 
Just in case, the new llama fails with Debian, so had to follow:
https://stackoverflow.com/questions/77586219/warning-cant-find-a-python-library-got-libdir-none-ldlibrary-none-multiarc
I'll be testing with chatGPT as the virtual envs at Yointly are quite basics just for testing and having fun

**Comment by gbrian** [comment]
Really cool! thanks. Will be great if you have time to connect and share.
image

**Pull request merged**
